###Задание1

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
#%config InlineBackend.figure_format = 'svg'
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg')

In [2]:
x = [1, 2, 3, 4, 5, 6, 7]
y = [3.5, 3.8, 4.2, 4.5, 5, 5.5, 7.]
#plt.interactive(True)
plt.plot(x, y)
#plt.savefig('test.png')
plt.show()

<Figure size 432x288 with 1 Axes>

In [3]:
plt.scatter(x, y)
plt.show()

<Figure size 432x288 with 1 Axes>

Задание2

In [4]:
t = np.linspace(0, 10, 51, dtype=float)
t

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [5]:
f = np.cos(t)
f

array([ 1.        ,  0.98006658,  0.92106099,  0.82533561,  0.69670671,
        0.54030231,  0.36235775,  0.16996714, -0.02919952, -0.22720209,
       -0.41614684, -0.58850112, -0.73739372, -0.85688875, -0.94222234,
       -0.9899925 , -0.99829478, -0.96679819, -0.89675842, -0.79096771,
       -0.65364362, -0.49026082, -0.30733287, -0.11215253,  0.08749898,
        0.28366219,  0.46851667,  0.63469288,  0.77556588,  0.88551952,
        0.96017029,  0.9965421 ,  0.99318492,  0.95023259,  0.86939749,
        0.75390225,  0.60835131,  0.43854733,  0.25125984,  0.05395542,
       -0.14550003, -0.33915486, -0.51928865, -0.67872005, -0.81109301,
       -0.91113026, -0.97484362, -0.99969304, -0.98468786, -0.93042627,
       -0.83907153])

In [6]:
plt.plot(t, f)
plt.axis([0.5, 9.5, -2.5, 2.5])
plt.title('График f(t)')
plt.xlabel('Значения t')
plt.ylabel('Значения f')
plt.show()

<Figure size 432x288 with 1 Axes>

###Задание3

In [7]:
x = np.linspace(-3, 3, 51, dtype=float)
x

array([-3.  , -2.88, -2.76, -2.64, -2.52, -2.4 , -2.28, -2.16, -2.04,
       -1.92, -1.8 , -1.68, -1.56, -1.44, -1.32, -1.2 , -1.08, -0.96,
       -0.84, -0.72, -0.6 , -0.48, -0.36, -0.24, -0.12,  0.  ,  0.12,
        0.24,  0.36,  0.48,  0.6 ,  0.72,  0.84,  0.96,  1.08,  1.2 ,
        1.32,  1.44,  1.56,  1.68,  1.8 ,  1.92,  2.04,  2.16,  2.28,
        2.4 ,  2.52,  2.64,  2.76,  2.88,  3.  ])

In [8]:
y1 = x**2
y1

array([9.    , 8.2944, 7.6176, 6.9696, 6.3504, 5.76  , 5.1984, 4.6656,
       4.1616, 3.6864, 3.24  , 2.8224, 2.4336, 2.0736, 1.7424, 1.44  ,
       1.1664, 0.9216, 0.7056, 0.5184, 0.36  , 0.2304, 0.1296, 0.0576,
       0.0144, 0.    , 0.0144, 0.0576, 0.1296, 0.2304, 0.36  , 0.5184,
       0.7056, 0.9216, 1.1664, 1.44  , 1.7424, 2.0736, 2.4336, 2.8224,
       3.24  , 3.6864, 4.1616, 4.6656, 5.1984, 5.76  , 6.3504, 6.9696,
       7.6176, 8.2944, 9.    ])

In [9]:
y2 = 2 * x + 0.5
y2

array([-5.5 , -5.26, -5.02, -4.78, -4.54, -4.3 , -4.06, -3.82, -3.58,
       -3.34, -3.1 , -2.86, -2.62, -2.38, -2.14, -1.9 , -1.66, -1.42,
       -1.18, -0.94, -0.7 , -0.46, -0.22,  0.02,  0.26,  0.5 ,  0.74,
        0.98,  1.22,  1.46,  1.7 ,  1.94,  2.18,  2.42,  2.66,  2.9 ,
        3.14,  3.38,  3.62,  3.86,  4.1 ,  4.34,  4.58,  4.82,  5.06,
        5.3 ,  5.54,  5.78,  6.02,  6.26,  6.5 ])

In [10]:
y3 = (-3 * x) - 1.5
y3

array([  7.5 ,   7.14,   6.78,   6.42,   6.06,   5.7 ,   5.34,   4.98,
         4.62,   4.26,   3.9 ,   3.54,   3.18,   2.82,   2.46,   2.1 ,
         1.74,   1.38,   1.02,   0.66,   0.3 ,  -0.06,  -0.42,  -0.78,
        -1.14,  -1.5 ,  -1.86,  -2.22,  -2.58,  -2.94,  -3.3 ,  -3.66,
        -4.02,  -4.38,  -4.74,  -5.1 ,  -5.46,  -5.82,  -6.18,  -6.54,
        -6.9 ,  -7.26,  -7.62,  -7.98,  -8.34,  -8.7 ,  -9.06,  -9.42,
        -9.78, -10.14, -10.5 ])

In [11]:
y4 = np.sin(x)
y4

array([-0.14112001, -0.25861935, -0.37239904, -0.48082261, -0.58233065,
       -0.67546318, -0.75888071, -0.83138346, -0.89192865, -0.93964547,
       -0.97384763, -0.9940432 , -0.99994172, -0.99145835, -0.9687151 ,
       -0.93203909, -0.88195781, -0.81919157, -0.74464312, -0.65938467,
       -0.56464247, -0.46177918, -0.35227423, -0.23770263, -0.11971221,
        0.        ,  0.11971221,  0.23770263,  0.35227423,  0.46177918,
        0.56464247,  0.65938467,  0.74464312,  0.81919157,  0.88195781,
        0.93203909,  0.9687151 ,  0.99145835,  0.99994172,  0.9940432 ,
        0.97384763,  0.93964547,  0.89192865,  0.83138346,  0.75888071,
        0.67546318,  0.58233065,  0.48082261,  0.37239904,  0.25861935,
        0.14112001])

In [12]:
fig, ax = plt.subplots(2, 2)
ax1, ax2, ax3, ax4 = ax.flatten()
ax1.plot(x, y1)
ax2.plot(x, y2)
ax3.plot(x, y3)
ax4.plot(x, y4)
ax1.set_title('График y1')
ax2.set_title('График y2')
ax3.set_title('График y3')
ax4.set_title('График y4')
ax1.set_xlim([-5, 5])
fig.set_size_inches(8, 6)
plt.subplots_adjust(wspace=0.3, hspace=0.3)


<Figure size 576x432 with 4 Axes>

Задание4

In [40]:
import os
#os.getcwd()
os.chdir('/Users/andreykorolev/PycharmProjects/GeekBrains/PythonForDS/Lesson3')
table = pd.DataFrame(pd.read_csv('creditcard.csv', encoding='utf8'))

In [52]:
z = table['Class'].value_counts()
z

0    284315
1       492
Name: Class, dtype: int64

In [55]:
z.plot('bar')
plt.show()

<Figure size 432x288 with 1 Axes>

In [56]:
z.plot('bar', logy=True)
plt.show()

<Figure size 432x288 with 1 Axes>

In [61]:
V1_0 = table.loc[table['Class'] == 0, 'V1']
V1_1 = table.loc[table['Class'] == 1, 'V1']

In [88]:
from pylab import rcParams
fig, ax = plt.subplots(1, 1)
fig.set_size_inches(7, 5)
#rcParams['figure.figsize'] = 6, 4.5
plt.hist(V1_0, bins=20, density=True, ec='white', alpha=0.5, color='grey')
plt.hist(V1_1, bins=20, density=True, ec='white', alpha=0.5, color='red')
plt.title('Транзакции')
plt.xlabel('Class')
plt.ylabel('Density')
plt.legend(labels=['Class 0','Class 1'])
plt.show()


<Figure size 504x360 with 1 Axes>