Задание1

In [16]:
import numpy as np
a = np.array(range(12, 24)) #еще можно было np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Задание2

In [53]:
a1 = a.reshape((2, 6))
a1

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [40]:
a2 = a.reshape((3, 4))
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
a3 = a.reshape((4, 3))
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [42]:
a4 = a.reshape((6, 2))
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [63]:
a5 = a.reshape((12, 1))
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Задание3

In [57]:
aa1 = np.reshape(a, (-1, 2))
aa1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [58]:
aa2 = np.reshape(a, (-1, 3))
aa2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [59]:
aa3 = np.reshape(a, (-1, 4))
aa3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
aa4 = np.reshape(a, (2, -1))
aa4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [64]:
aa5 = np.reshape(a, (12, -1))
aa5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Задание4

In [67]:
aa5.shape #нет, нельзя назвать массив одномерным

(12, 1)

Задание5

In [118]:
b = np.random.randn(3, 4)
b

array([[ 1.91711799,  0.97696177, -0.23324496, -1.04246063],
       [-0.02116489,  1.14283822, -1.07611274,  0.77973325],
       [ 0.83903085, -0.31533732,  1.04661805, -0.96189747]])

In [119]:
c = b.flatten()
c

array([ 1.91711799,  0.97696177, -0.23324496, -1.04246063, -0.02116489,
        1.14283822, -1.07611274,  0.77973325,  0.83903085, -0.31533732,
        1.04661805, -0.96189747])

In [120]:
b.size == c.size

True

Задание6

In [142]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [143]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [147]:
a.shape

(10,)

In [148]:
b.shape

(1, 10)

Задание7

In [150]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [151]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [153]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [154]:
v.size

10

Задание8

In [163]:
a = np.arange(0, 12)
A = np.reshape(a, (4, 3))
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [164]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [165]:
B.size

16

In [168]:
#B_inv = np.linalg.inv(B)
np.linalg.det(B) #Определитель матрицы B равен 0, поэтому вычислить обратную матрицу нельзя

0.0

Задание9

In [182]:
np.random.seed(42)
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [183]:
C = np.reshape(c, (4, 4))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [184]:
D = (C * 10) + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [185]:
np.linalg.det(D)

-28511999.999999944

In [186]:
np.linalg.matrix_rank(D)

4

In [188]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

Задача10

In [196]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [199]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [200]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [198]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])