###Задача1


In [32]:
import numpy as np
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
N = 5
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [33]:
a.mean(axis=0)

array([2. , 8.4])

In [34]:
mean_a = a.mean(axis=0)

###Задача2

In [35]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

###Задача3

In [36]:
c = a_centered[0:, 0]
c

array([-1.,  0.,  1.,  1., -1.])

In [37]:
d = a_centered[0:, 1]
d

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [38]:
a_centered_sp = np.dot(c, d)
a_centered_sp

8.0

In [39]:
a_centered_sp / (N-1)


2.0

###Задача4

In [44]:
m = a.T
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [49]:
k = np.cov(m)
k

array([[1. , 2. ],
       [2. , 4.3]])

In [50]:
k[0, 1]

2.0